package com.bsms.app.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bsms.app.model.TblEeqUser;
import com.bsms.app.model.TblEeqUserExample;

public interface TblEeqUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    long countByExample(TblEeqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int deleteByExample(TblEeqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int deleteByPrimaryKey(Long pkEeqUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int insert(TblEeqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int insertSelective(TblEeqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    List<TblEeqUser> selectByExample(TblEeqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    TblEeqUser selectByPrimaryKey(Long pkEeqUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") TblEeqUser record, @Param("example") TblEeqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int updateByExample(@Param("record") TblEeqUser record, @Param("example") TblEeqUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int updateByPrimaryKeySelective(TblEeqUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    int updateByPrimaryKey(TblEeqUser record);
}