package com.bsms.app.model;

public class TblDicParam extends Page{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.pk_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private Long pkDicParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_code
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String paramCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_name
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_desc
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String paramDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_order
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private Integer paramOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.parent_code
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.field1
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.crt_time
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.upd_time
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.obj_version
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private Integer objVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.flag_enable
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String flagEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.usage_key
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String usageKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_desc2
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String paramDesc2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_desc3
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String paramDesc3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_param.param_system
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    private String paramSystem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.pk_dic_param
     *
     * @return the value of tbl_dic_param.pk_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public Long getPkDicParam() {
        return pkDicParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.pk_dic_param
     *
     * @param pkDicParam the value for tbl_dic_param.pk_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setPkDicParam(Long pkDicParam) {
        this.pkDicParam = pkDicParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_code
     *
     * @return the value of tbl_dic_param.param_code
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_code
     *
     * @param paramCode the value for tbl_dic_param.param_code
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_name
     *
     * @return the value of tbl_dic_param.param_name
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_name
     *
     * @param paramName the value for tbl_dic_param.param_name
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_desc
     *
     * @return the value of tbl_dic_param.param_desc
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_desc
     *
     * @param paramDesc the value for tbl_dic_param.param_desc
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_order
     *
     * @return the value of tbl_dic_param.param_order
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public Integer getParamOrder() {
        return paramOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_order
     *
     * @param paramOrder the value for tbl_dic_param.param_order
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamOrder(Integer paramOrder) {
        this.paramOrder = paramOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.parent_code
     *
     * @return the value of tbl_dic_param.parent_code
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.parent_code
     *
     * @param parentCode the value for tbl_dic_param.parent_code
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.field1
     *
     * @return the value of tbl_dic_param.field1
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.field1
     *
     * @param field1 the value for tbl_dic_param.field1
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setField1(String field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.crt_time
     *
     * @return the value of tbl_dic_param.crt_time
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.crt_time
     *
     * @param crtTime the value for tbl_dic_param.crt_time
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setCrtTime(String crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.upd_time
     *
     * @return the value of tbl_dic_param.upd_time
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.upd_time
     *
     * @param updTime the value for tbl_dic_param.upd_time
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setUpdTime(String updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.obj_version
     *
     * @return the value of tbl_dic_param.obj_version
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public Integer getObjVersion() {
        return objVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.obj_version
     *
     * @param objVersion the value for tbl_dic_param.obj_version
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setObjVersion(Integer objVersion) {
        this.objVersion = objVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.flag_enable
     *
     * @return the value of tbl_dic_param.flag_enable
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.flag_enable
     *
     * @param flagEnable the value for tbl_dic_param.flag_enable
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setFlagEnable(String flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.usage_key
     *
     * @return the value of tbl_dic_param.usage_key
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getUsageKey() {
        return usageKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.usage_key
     *
     * @param usageKey the value for tbl_dic_param.usage_key
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setUsageKey(String usageKey) {
        this.usageKey = usageKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_desc2
     *
     * @return the value of tbl_dic_param.param_desc2
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParamDesc2() {
        return paramDesc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_desc2
     *
     * @param paramDesc2 the value for tbl_dic_param.param_desc2
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamDesc2(String paramDesc2) {
        this.paramDesc2 = paramDesc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_desc3
     *
     * @return the value of tbl_dic_param.param_desc3
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParamDesc3() {
        return paramDesc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_desc3
     *
     * @param paramDesc3 the value for tbl_dic_param.param_desc3
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamDesc3(String paramDesc3) {
        this.paramDesc3 = paramDesc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dic_param.param_system
     *
     * @return the value of tbl_dic_param.param_system
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getParamSystem() {
        return paramSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dic_param.param_system
     *
     * @param paramSystem the value for tbl_dic_param.param_system
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setParamSystem(String paramSystem) {
        this.paramSystem = paramSystem;
    }
}