package com.bsms.app.model;

import java.util.ArrayList;
import java.util.List;

public class TblDicParamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public TblDicParamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkDicParamIsNull() {
            addCriterion("pk_dic_param is null");
            return (Criteria) this;
        }

        public Criteria andPkDicParamIsNotNull() {
            addCriterion("pk_dic_param is not null");
            return (Criteria) this;
        }

        public Criteria andPkDicParamEqualTo(Long value) {
            addCriterion("pk_dic_param =", value, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamNotEqualTo(Long value) {
            addCriterion("pk_dic_param <>", value, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamGreaterThan(Long value) {
            addCriterion("pk_dic_param >", value, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamGreaterThanOrEqualTo(Long value) {
            addCriterion("pk_dic_param >=", value, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamLessThan(Long value) {
            addCriterion("pk_dic_param <", value, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamLessThanOrEqualTo(Long value) {
            addCriterion("pk_dic_param <=", value, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamIn(List<Long> values) {
            addCriterion("pk_dic_param in", values, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamNotIn(List<Long> values) {
            addCriterion("pk_dic_param not in", values, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamBetween(Long value1, Long value2) {
            addCriterion("pk_dic_param between", value1, value2, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andPkDicParamNotBetween(Long value1, Long value2) {
            addCriterion("pk_dic_param not between", value1, value2, "pkDicParam");
            return (Criteria) this;
        }

        public Criteria andParamCodeIsNull() {
            addCriterion("param_code is null");
            return (Criteria) this;
        }

        public Criteria andParamCodeIsNotNull() {
            addCriterion("param_code is not null");
            return (Criteria) this;
        }

        public Criteria andParamCodeEqualTo(String value) {
            addCriterion("param_code =", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeNotEqualTo(String value) {
            addCriterion("param_code <>", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeGreaterThan(String value) {
            addCriterion("param_code >", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeGreaterThanOrEqualTo(String value) {
            addCriterion("param_code >=", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeLessThan(String value) {
            addCriterion("param_code <", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeLessThanOrEqualTo(String value) {
            addCriterion("param_code <=", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeLike(String value) {
            addCriterion("param_code like", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeNotLike(String value) {
            addCriterion("param_code not like", value, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeIn(List<String> values) {
            addCriterion("param_code in", values, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeNotIn(List<String> values) {
            addCriterion("param_code not in", values, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeBetween(String value1, String value2) {
            addCriterion("param_code between", value1, value2, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamCodeNotBetween(String value1, String value2) {
            addCriterion("param_code not between", value1, value2, "paramCode");
            return (Criteria) this;
        }

        public Criteria andParamNameIsNull() {
            addCriterion("param_name is null");
            return (Criteria) this;
        }

        public Criteria andParamNameIsNotNull() {
            addCriterion("param_name is not null");
            return (Criteria) this;
        }

        public Criteria andParamNameEqualTo(String value) {
            addCriterion("param_name =", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameNotEqualTo(String value) {
            addCriterion("param_name <>", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameGreaterThan(String value) {
            addCriterion("param_name >", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameGreaterThanOrEqualTo(String value) {
            addCriterion("param_name >=", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameLessThan(String value) {
            addCriterion("param_name <", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameLessThanOrEqualTo(String value) {
            addCriterion("param_name <=", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameLike(String value) {
            addCriterion("param_name like", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameNotLike(String value) {
            addCriterion("param_name not like", value, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameIn(List<String> values) {
            addCriterion("param_name in", values, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameNotIn(List<String> values) {
            addCriterion("param_name not in", values, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameBetween(String value1, String value2) {
            addCriterion("param_name between", value1, value2, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamNameNotBetween(String value1, String value2) {
            addCriterion("param_name not between", value1, value2, "paramName");
            return (Criteria) this;
        }

        public Criteria andParamDescIsNull() {
            addCriterion("param_desc is null");
            return (Criteria) this;
        }

        public Criteria andParamDescIsNotNull() {
            addCriterion("param_desc is not null");
            return (Criteria) this;
        }

        public Criteria andParamDescEqualTo(String value) {
            addCriterion("param_desc =", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescNotEqualTo(String value) {
            addCriterion("param_desc <>", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescGreaterThan(String value) {
            addCriterion("param_desc >", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescGreaterThanOrEqualTo(String value) {
            addCriterion("param_desc >=", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescLessThan(String value) {
            addCriterion("param_desc <", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescLessThanOrEqualTo(String value) {
            addCriterion("param_desc <=", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescLike(String value) {
            addCriterion("param_desc like", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescNotLike(String value) {
            addCriterion("param_desc not like", value, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescIn(List<String> values) {
            addCriterion("param_desc in", values, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescNotIn(List<String> values) {
            addCriterion("param_desc not in", values, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescBetween(String value1, String value2) {
            addCriterion("param_desc between", value1, value2, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamDescNotBetween(String value1, String value2) {
            addCriterion("param_desc not between", value1, value2, "paramDesc");
            return (Criteria) this;
        }

        public Criteria andParamOrderIsNull() {
            addCriterion("param_order is null");
            return (Criteria) this;
        }

        public Criteria andParamOrderIsNotNull() {
            addCriterion("param_order is not null");
            return (Criteria) this;
        }

        public Criteria andParamOrderEqualTo(Integer value) {
            addCriterion("param_order =", value, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderNotEqualTo(Integer value) {
            addCriterion("param_order <>", value, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderGreaterThan(Integer value) {
            addCriterion("param_order >", value, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("param_order >=", value, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderLessThan(Integer value) {
            addCriterion("param_order <", value, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderLessThanOrEqualTo(Integer value) {
            addCriterion("param_order <=", value, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderIn(List<Integer> values) {
            addCriterion("param_order in", values, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderNotIn(List<Integer> values) {
            addCriterion("param_order not in", values, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderBetween(Integer value1, Integer value2) {
            addCriterion("param_order between", value1, value2, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParamOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("param_order not between", value1, value2, "paramOrder");
            return (Criteria) this;
        }

        public Criteria andParentCodeIsNull() {
            addCriterion("parent_code is null");
            return (Criteria) this;
        }

        public Criteria andParentCodeIsNotNull() {
            addCriterion("parent_code is not null");
            return (Criteria) this;
        }

        public Criteria andParentCodeEqualTo(String value) {
            addCriterion("parent_code =", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotEqualTo(String value) {
            addCriterion("parent_code <>", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeGreaterThan(String value) {
            addCriterion("parent_code >", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("parent_code >=", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLessThan(String value) {
            addCriterion("parent_code <", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLessThanOrEqualTo(String value) {
            addCriterion("parent_code <=", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLike(String value) {
            addCriterion("parent_code like", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotLike(String value) {
            addCriterion("parent_code not like", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeIn(List<String> values) {
            addCriterion("parent_code in", values, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotIn(List<String> values) {
            addCriterion("parent_code not in", values, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeBetween(String value1, String value2) {
            addCriterion("parent_code between", value1, value2, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotBetween(String value1, String value2) {
            addCriterion("parent_code not between", value1, value2, "parentCode");
            return (Criteria) this;
        }

        public Criteria andField1IsNull() {
            addCriterion("field1 is null");
            return (Criteria) this;
        }

        public Criteria andField1IsNotNull() {
            addCriterion("field1 is not null");
            return (Criteria) this;
        }

        public Criteria andField1EqualTo(String value) {
            addCriterion("field1 =", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotEqualTo(String value) {
            addCriterion("field1 <>", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThan(String value) {
            addCriterion("field1 >", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThanOrEqualTo(String value) {
            addCriterion("field1 >=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThan(String value) {
            addCriterion("field1 <", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThanOrEqualTo(String value) {
            addCriterion("field1 <=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Like(String value) {
            addCriterion("field1 like", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotLike(String value) {
            addCriterion("field1 not like", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1In(List<String> values) {
            addCriterion("field1 in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotIn(List<String> values) {
            addCriterion("field1 not in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Between(String value1, String value2) {
            addCriterion("field1 between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotBetween(String value1, String value2) {
            addCriterion("field1 not between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("crt_time is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("crt_time is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(String value) {
            addCriterion("crt_time =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(String value) {
            addCriterion("crt_time <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(String value) {
            addCriterion("crt_time >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(String value) {
            addCriterion("crt_time >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(String value) {
            addCriterion("crt_time <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(String value) {
            addCriterion("crt_time <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLike(String value) {
            addCriterion("crt_time like", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotLike(String value) {
            addCriterion("crt_time not like", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<String> values) {
            addCriterion("crt_time in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<String> values) {
            addCriterion("crt_time not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(String value1, String value2) {
            addCriterion("crt_time between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(String value1, String value2) {
            addCriterion("crt_time not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(String value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(String value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(String value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(String value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(String value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(String value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLike(String value) {
            addCriterion("upd_time like", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotLike(String value) {
            addCriterion("upd_time not like", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<String> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<String> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(String value1, String value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(String value1, String value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andObjVersionIsNull() {
            addCriterion("obj_version is null");
            return (Criteria) this;
        }

        public Criteria andObjVersionIsNotNull() {
            addCriterion("obj_version is not null");
            return (Criteria) this;
        }

        public Criteria andObjVersionEqualTo(Integer value) {
            addCriterion("obj_version =", value, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionNotEqualTo(Integer value) {
            addCriterion("obj_version <>", value, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionGreaterThan(Integer value) {
            addCriterion("obj_version >", value, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("obj_version >=", value, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionLessThan(Integer value) {
            addCriterion("obj_version <", value, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionLessThanOrEqualTo(Integer value) {
            addCriterion("obj_version <=", value, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionIn(List<Integer> values) {
            addCriterion("obj_version in", values, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionNotIn(List<Integer> values) {
            addCriterion("obj_version not in", values, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionBetween(Integer value1, Integer value2) {
            addCriterion("obj_version between", value1, value2, "objVersion");
            return (Criteria) this;
        }

        public Criteria andObjVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("obj_version not between", value1, value2, "objVersion");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNull() {
            addCriterion("flag_enable is null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNotNull() {
            addCriterion("flag_enable is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableEqualTo(String value) {
            addCriterion("flag_enable =", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotEqualTo(String value) {
            addCriterion("flag_enable <>", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThan(String value) {
            addCriterion("flag_enable >", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThanOrEqualTo(String value) {
            addCriterion("flag_enable >=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThan(String value) {
            addCriterion("flag_enable <", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThanOrEqualTo(String value) {
            addCriterion("flag_enable <=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLike(String value) {
            addCriterion("flag_enable like", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotLike(String value) {
            addCriterion("flag_enable not like", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIn(List<String> values) {
            addCriterion("flag_enable in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotIn(List<String> values) {
            addCriterion("flag_enable not in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableBetween(String value1, String value2) {
            addCriterion("flag_enable between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotBetween(String value1, String value2) {
            addCriterion("flag_enable not between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andUsageKeyIsNull() {
            addCriterion("usage_key is null");
            return (Criteria) this;
        }

        public Criteria andUsageKeyIsNotNull() {
            addCriterion("usage_key is not null");
            return (Criteria) this;
        }

        public Criteria andUsageKeyEqualTo(String value) {
            addCriterion("usage_key =", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyNotEqualTo(String value) {
            addCriterion("usage_key <>", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyGreaterThan(String value) {
            addCriterion("usage_key >", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyGreaterThanOrEqualTo(String value) {
            addCriterion("usage_key >=", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyLessThan(String value) {
            addCriterion("usage_key <", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyLessThanOrEqualTo(String value) {
            addCriterion("usage_key <=", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyLike(String value) {
            addCriterion("usage_key like", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyNotLike(String value) {
            addCriterion("usage_key not like", value, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyIn(List<String> values) {
            addCriterion("usage_key in", values, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyNotIn(List<String> values) {
            addCriterion("usage_key not in", values, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyBetween(String value1, String value2) {
            addCriterion("usage_key between", value1, value2, "usageKey");
            return (Criteria) this;
        }

        public Criteria andUsageKeyNotBetween(String value1, String value2) {
            addCriterion("usage_key not between", value1, value2, "usageKey");
            return (Criteria) this;
        }

        public Criteria andParamDesc2IsNull() {
            addCriterion("param_desc2 is null");
            return (Criteria) this;
        }

        public Criteria andParamDesc2IsNotNull() {
            addCriterion("param_desc2 is not null");
            return (Criteria) this;
        }

        public Criteria andParamDesc2EqualTo(String value) {
            addCriterion("param_desc2 =", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2NotEqualTo(String value) {
            addCriterion("param_desc2 <>", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2GreaterThan(String value) {
            addCriterion("param_desc2 >", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2GreaterThanOrEqualTo(String value) {
            addCriterion("param_desc2 >=", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2LessThan(String value) {
            addCriterion("param_desc2 <", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2LessThanOrEqualTo(String value) {
            addCriterion("param_desc2 <=", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2Like(String value) {
            addCriterion("param_desc2 like", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2NotLike(String value) {
            addCriterion("param_desc2 not like", value, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2In(List<String> values) {
            addCriterion("param_desc2 in", values, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2NotIn(List<String> values) {
            addCriterion("param_desc2 not in", values, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2Between(String value1, String value2) {
            addCriterion("param_desc2 between", value1, value2, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc2NotBetween(String value1, String value2) {
            addCriterion("param_desc2 not between", value1, value2, "paramDesc2");
            return (Criteria) this;
        }

        public Criteria andParamDesc3IsNull() {
            addCriterion("param_desc3 is null");
            return (Criteria) this;
        }

        public Criteria andParamDesc3IsNotNull() {
            addCriterion("param_desc3 is not null");
            return (Criteria) this;
        }

        public Criteria andParamDesc3EqualTo(String value) {
            addCriterion("param_desc3 =", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3NotEqualTo(String value) {
            addCriterion("param_desc3 <>", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3GreaterThan(String value) {
            addCriterion("param_desc3 >", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3GreaterThanOrEqualTo(String value) {
            addCriterion("param_desc3 >=", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3LessThan(String value) {
            addCriterion("param_desc3 <", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3LessThanOrEqualTo(String value) {
            addCriterion("param_desc3 <=", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3Like(String value) {
            addCriterion("param_desc3 like", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3NotLike(String value) {
            addCriterion("param_desc3 not like", value, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3In(List<String> values) {
            addCriterion("param_desc3 in", values, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3NotIn(List<String> values) {
            addCriterion("param_desc3 not in", values, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3Between(String value1, String value2) {
            addCriterion("param_desc3 between", value1, value2, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamDesc3NotBetween(String value1, String value2) {
            addCriterion("param_desc3 not between", value1, value2, "paramDesc3");
            return (Criteria) this;
        }

        public Criteria andParamSystemIsNull() {
            addCriterion("param_system is null");
            return (Criteria) this;
        }

        public Criteria andParamSystemIsNotNull() {
            addCriterion("param_system is not null");
            return (Criteria) this;
        }

        public Criteria andParamSystemEqualTo(String value) {
            addCriterion("param_system =", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemNotEqualTo(String value) {
            addCriterion("param_system <>", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemGreaterThan(String value) {
            addCriterion("param_system >", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemGreaterThanOrEqualTo(String value) {
            addCriterion("param_system >=", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemLessThan(String value) {
            addCriterion("param_system <", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemLessThanOrEqualTo(String value) {
            addCriterion("param_system <=", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemLike(String value) {
            addCriterion("param_system like", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemNotLike(String value) {
            addCriterion("param_system not like", value, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemIn(List<String> values) {
            addCriterion("param_system in", values, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemNotIn(List<String> values) {
            addCriterion("param_system not in", values, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemBetween(String value1, String value2) {
            addCriterion("param_system between", value1, value2, "paramSystem");
            return (Criteria) this;
        }

        public Criteria andParamSystemNotBetween(String value1, String value2) {
            addCriterion("param_system not between", value1, value2, "paramSystem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_dic_param
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 16 12:25:58 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_dic_param
     *
     * @mbg.generated Fri Nov 16 12:25:58 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}