package com.bsms.app.model;

import java.util.ArrayList;
import java.util.List;

public class TblEeqUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public TblEeqUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkEeqUserIsNull() {
            addCriterion("pk_eeq_user is null");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserIsNotNull() {
            addCriterion("pk_eeq_user is not null");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserEqualTo(Long value) {
            addCriterion("pk_eeq_user =", value, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserNotEqualTo(Long value) {
            addCriterion("pk_eeq_user <>", value, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserGreaterThan(Long value) {
            addCriterion("pk_eeq_user >", value, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserGreaterThanOrEqualTo(Long value) {
            addCriterion("pk_eeq_user >=", value, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserLessThan(Long value) {
            addCriterion("pk_eeq_user <", value, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserLessThanOrEqualTo(Long value) {
            addCriterion("pk_eeq_user <=", value, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserIn(List<Long> values) {
            addCriterion("pk_eeq_user in", values, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserNotIn(List<Long> values) {
            addCriterion("pk_eeq_user not in", values, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserBetween(Long value1, Long value2) {
            addCriterion("pk_eeq_user between", value1, value2, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andPkEeqUserNotBetween(Long value1, Long value2) {
            addCriterion("pk_eeq_user not between", value1, value2, "pkEeqUser");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNull() {
            addCriterion("dept_code is null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNotNull() {
            addCriterion("dept_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeEqualTo(String value) {
            addCriterion("dept_code =", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotEqualTo(String value) {
            addCriterion("dept_code <>", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThan(String value) {
            addCriterion("dept_code >", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dept_code >=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThan(String value) {
            addCriterion("dept_code <", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThanOrEqualTo(String value) {
            addCriterion("dept_code <=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLike(String value) {
            addCriterion("dept_code like", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotLike(String value) {
            addCriterion("dept_code not like", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIn(List<String> values) {
            addCriterion("dept_code in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotIn(List<String> values) {
            addCriterion("dept_code not in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeBetween(String value1, String value2) {
            addCriterion("dept_code between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotBetween(String value1, String value2) {
            addCriterion("dept_code not between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andBranIdIsNull() {
            addCriterion("bran_id is null");
            return (Criteria) this;
        }

        public Criteria andBranIdIsNotNull() {
            addCriterion("bran_id is not null");
            return (Criteria) this;
        }

        public Criteria andBranIdEqualTo(String value) {
            addCriterion("bran_id =", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdNotEqualTo(String value) {
            addCriterion("bran_id <>", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdGreaterThan(String value) {
            addCriterion("bran_id >", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdGreaterThanOrEqualTo(String value) {
            addCriterion("bran_id >=", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdLessThan(String value) {
            addCriterion("bran_id <", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdLessThanOrEqualTo(String value) {
            addCriterion("bran_id <=", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdLike(String value) {
            addCriterion("bran_id like", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdNotLike(String value) {
            addCriterion("bran_id not like", value, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdIn(List<String> values) {
            addCriterion("bran_id in", values, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdNotIn(List<String> values) {
            addCriterion("bran_id not in", values, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdBetween(String value1, String value2) {
            addCriterion("bran_id between", value1, value2, "branId");
            return (Criteria) this;
        }

        public Criteria andBranIdNotBetween(String value1, String value2) {
            addCriterion("bran_id not between", value1, value2, "branId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserPwdIsNull() {
            addCriterion("user_pwd is null");
            return (Criteria) this;
        }

        public Criteria andUserPwdIsNotNull() {
            addCriterion("user_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andUserPwdEqualTo(String value) {
            addCriterion("user_pwd =", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotEqualTo(String value) {
            addCriterion("user_pwd <>", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdGreaterThan(String value) {
            addCriterion("user_pwd >", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdGreaterThanOrEqualTo(String value) {
            addCriterion("user_pwd >=", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLessThan(String value) {
            addCriterion("user_pwd <", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLessThanOrEqualTo(String value) {
            addCriterion("user_pwd <=", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLike(String value) {
            addCriterion("user_pwd like", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotLike(String value) {
            addCriterion("user_pwd not like", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdIn(List<String> values) {
            addCriterion("user_pwd in", values, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotIn(List<String> values) {
            addCriterion("user_pwd not in", values, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdBetween(String value1, String value2) {
            addCriterion("user_pwd between", value1, value2, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotBetween(String value1, String value2) {
            addCriterion("user_pwd not between", value1, value2, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNull() {
            addCriterion("user_state is null");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNotNull() {
            addCriterion("user_state is not null");
            return (Criteria) this;
        }

        public Criteria andUserStateEqualTo(String value) {
            addCriterion("user_state =", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotEqualTo(String value) {
            addCriterion("user_state <>", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThan(String value) {
            addCriterion("user_state >", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThanOrEqualTo(String value) {
            addCriterion("user_state >=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThan(String value) {
            addCriterion("user_state <", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThanOrEqualTo(String value) {
            addCriterion("user_state <=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLike(String value) {
            addCriterion("user_state like", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotLike(String value) {
            addCriterion("user_state not like", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateIn(List<String> values) {
            addCriterion("user_state in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotIn(List<String> values) {
            addCriterion("user_state not in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateBetween(String value1, String value2) {
            addCriterion("user_state between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotBetween(String value1, String value2) {
            addCriterion("user_state not between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNull() {
            addCriterion("tel_no is null");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNotNull() {
            addCriterion("tel_no is not null");
            return (Criteria) this;
        }

        public Criteria andTelNoEqualTo(String value) {
            addCriterion("tel_no =", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotEqualTo(String value) {
            addCriterion("tel_no <>", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThan(String value) {
            addCriterion("tel_no >", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("tel_no >=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThan(String value) {
            addCriterion("tel_no <", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThanOrEqualTo(String value) {
            addCriterion("tel_no <=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLike(String value) {
            addCriterion("tel_no like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotLike(String value) {
            addCriterion("tel_no not like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoIn(List<String> values) {
            addCriterion("tel_no in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotIn(List<String> values) {
            addCriterion("tel_no not in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoBetween(String value1, String value2) {
            addCriterion("tel_no between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotBetween(String value1, String value2) {
            addCriterion("tel_no not between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoIsNull() {
            addCriterion("fax_no is null");
            return (Criteria) this;
        }

        public Criteria andFaxNoIsNotNull() {
            addCriterion("fax_no is not null");
            return (Criteria) this;
        }

        public Criteria andFaxNoEqualTo(String value) {
            addCriterion("fax_no =", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoNotEqualTo(String value) {
            addCriterion("fax_no <>", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoGreaterThan(String value) {
            addCriterion("fax_no >", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoGreaterThanOrEqualTo(String value) {
            addCriterion("fax_no >=", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoLessThan(String value) {
            addCriterion("fax_no <", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoLessThanOrEqualTo(String value) {
            addCriterion("fax_no <=", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoLike(String value) {
            addCriterion("fax_no like", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoNotLike(String value) {
            addCriterion("fax_no not like", value, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoIn(List<String> values) {
            addCriterion("fax_no in", values, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoNotIn(List<String> values) {
            addCriterion("fax_no not in", values, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoBetween(String value1, String value2) {
            addCriterion("fax_no between", value1, value2, "faxNo");
            return (Criteria) this;
        }

        public Criteria andFaxNoNotBetween(String value1, String value2) {
            addCriterion("fax_no not between", value1, value2, "faxNo");
            return (Criteria) this;
        }

        public Criteria andEmailAddrIsNull() {
            addCriterion("email_addr is null");
            return (Criteria) this;
        }

        public Criteria andEmailAddrIsNotNull() {
            addCriterion("email_addr is not null");
            return (Criteria) this;
        }

        public Criteria andEmailAddrEqualTo(String value) {
            addCriterion("email_addr =", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrNotEqualTo(String value) {
            addCriterion("email_addr <>", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrGreaterThan(String value) {
            addCriterion("email_addr >", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrGreaterThanOrEqualTo(String value) {
            addCriterion("email_addr >=", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrLessThan(String value) {
            addCriterion("email_addr <", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrLessThanOrEqualTo(String value) {
            addCriterion("email_addr <=", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrLike(String value) {
            addCriterion("email_addr like", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrNotLike(String value) {
            addCriterion("email_addr not like", value, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrIn(List<String> values) {
            addCriterion("email_addr in", values, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrNotIn(List<String> values) {
            addCriterion("email_addr not in", values, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrBetween(String value1, String value2) {
            addCriterion("email_addr between", value1, value2, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andEmailAddrNotBetween(String value1, String value2) {
            addCriterion("email_addr not between", value1, value2, "emailAddr");
            return (Criteria) this;
        }

        public Criteria andLstinTimeIsNull() {
            addCriterion("lstin_time is null");
            return (Criteria) this;
        }

        public Criteria andLstinTimeIsNotNull() {
            addCriterion("lstin_time is not null");
            return (Criteria) this;
        }

        public Criteria andLstinTimeEqualTo(String value) {
            addCriterion("lstin_time =", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeNotEqualTo(String value) {
            addCriterion("lstin_time <>", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeGreaterThan(String value) {
            addCriterion("lstin_time >", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeGreaterThanOrEqualTo(String value) {
            addCriterion("lstin_time >=", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeLessThan(String value) {
            addCriterion("lstin_time <", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeLessThanOrEqualTo(String value) {
            addCriterion("lstin_time <=", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeLike(String value) {
            addCriterion("lstin_time like", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeNotLike(String value) {
            addCriterion("lstin_time not like", value, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeIn(List<String> values) {
            addCriterion("lstin_time in", values, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeNotIn(List<String> values) {
            addCriterion("lstin_time not in", values, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeBetween(String value1, String value2) {
            addCriterion("lstin_time between", value1, value2, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstinTimeNotBetween(String value1, String value2) {
            addCriterion("lstin_time not between", value1, value2, "lstinTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeIsNull() {
            addCriterion("lstout_time is null");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeIsNotNull() {
            addCriterion("lstout_time is not null");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeEqualTo(String value) {
            addCriterion("lstout_time =", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeNotEqualTo(String value) {
            addCriterion("lstout_time <>", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeGreaterThan(String value) {
            addCriterion("lstout_time >", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeGreaterThanOrEqualTo(String value) {
            addCriterion("lstout_time >=", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeLessThan(String value) {
            addCriterion("lstout_time <", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeLessThanOrEqualTo(String value) {
            addCriterion("lstout_time <=", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeLike(String value) {
            addCriterion("lstout_time like", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeNotLike(String value) {
            addCriterion("lstout_time not like", value, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeIn(List<String> values) {
            addCriterion("lstout_time in", values, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeNotIn(List<String> values) {
            addCriterion("lstout_time not in", values, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeBetween(String value1, String value2) {
            addCriterion("lstout_time between", value1, value2, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andLstoutTimeNotBetween(String value1, String value2) {
            addCriterion("lstout_time not between", value1, value2, "lstoutTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeIsNull() {
            addCriterion("chgpwd_time is null");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeIsNotNull() {
            addCriterion("chgpwd_time is not null");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeEqualTo(String value) {
            addCriterion("chgpwd_time =", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeNotEqualTo(String value) {
            addCriterion("chgpwd_time <>", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeGreaterThan(String value) {
            addCriterion("chgpwd_time >", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeGreaterThanOrEqualTo(String value) {
            addCriterion("chgpwd_time >=", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeLessThan(String value) {
            addCriterion("chgpwd_time <", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeLessThanOrEqualTo(String value) {
            addCriterion("chgpwd_time <=", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeLike(String value) {
            addCriterion("chgpwd_time like", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeNotLike(String value) {
            addCriterion("chgpwd_time not like", value, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeIn(List<String> values) {
            addCriterion("chgpwd_time in", values, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeNotIn(List<String> values) {
            addCriterion("chgpwd_time not in", values, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeBetween(String value1, String value2) {
            addCriterion("chgpwd_time between", value1, value2, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andChgpwdTimeNotBetween(String value1, String value2) {
            addCriterion("chgpwd_time not between", value1, value2, "chgpwdTime");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("session_id is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("session_id is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("session_id =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("session_id <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("session_id >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("session_id >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("session_id <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("session_id <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("session_id like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("session_id not like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("session_id in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("session_id not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("session_id between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("session_id not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andCurStateIsNull() {
            addCriterion("cur_state is null");
            return (Criteria) this;
        }

        public Criteria andCurStateIsNotNull() {
            addCriterion("cur_state is not null");
            return (Criteria) this;
        }

        public Criteria andCurStateEqualTo(String value) {
            addCriterion("cur_state =", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateNotEqualTo(String value) {
            addCriterion("cur_state <>", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateGreaterThan(String value) {
            addCriterion("cur_state >", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateGreaterThanOrEqualTo(String value) {
            addCriterion("cur_state >=", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateLessThan(String value) {
            addCriterion("cur_state <", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateLessThanOrEqualTo(String value) {
            addCriterion("cur_state <=", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateLike(String value) {
            addCriterion("cur_state like", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateNotLike(String value) {
            addCriterion("cur_state not like", value, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateIn(List<String> values) {
            addCriterion("cur_state in", values, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateNotIn(List<String> values) {
            addCriterion("cur_state not in", values, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateBetween(String value1, String value2) {
            addCriterion("cur_state between", value1, value2, "curState");
            return (Criteria) this;
        }

        public Criteria andCurStateNotBetween(String value1, String value2) {
            addCriterion("cur_state not between", value1, value2, "curState");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdIsNull() {
            addCriterion("crt_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdIsNotNull() {
            addCriterion("crt_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdEqualTo(String value) {
            addCriterion("crt_user_id =", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdNotEqualTo(String value) {
            addCriterion("crt_user_id <>", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdGreaterThan(String value) {
            addCriterion("crt_user_id >", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("crt_user_id >=", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdLessThan(String value) {
            addCriterion("crt_user_id <", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdLessThanOrEqualTo(String value) {
            addCriterion("crt_user_id <=", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdLike(String value) {
            addCriterion("crt_user_id like", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdNotLike(String value) {
            addCriterion("crt_user_id not like", value, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdIn(List<String> values) {
            addCriterion("crt_user_id in", values, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdNotIn(List<String> values) {
            addCriterion("crt_user_id not in", values, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdBetween(String value1, String value2) {
            addCriterion("crt_user_id between", value1, value2, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtUserIdNotBetween(String value1, String value2) {
            addCriterion("crt_user_id not between", value1, value2, "crtUserId");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("crt_time is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("crt_time is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(String value) {
            addCriterion("crt_time =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(String value) {
            addCriterion("crt_time <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(String value) {
            addCriterion("crt_time >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(String value) {
            addCriterion("crt_time >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(String value) {
            addCriterion("crt_time <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(String value) {
            addCriterion("crt_time <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLike(String value) {
            addCriterion("crt_time like", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotLike(String value) {
            addCriterion("crt_time not like", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<String> values) {
            addCriterion("crt_time in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<String> values) {
            addCriterion("crt_time not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(String value1, String value2) {
            addCriterion("crt_time between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(String value1, String value2) {
            addCriterion("crt_time not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNull() {
            addCriterion("upd_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIsNotNull() {
            addCriterion("upd_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdEqualTo(String value) {
            addCriterion("upd_user_id =", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotEqualTo(String value) {
            addCriterion("upd_user_id <>", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThan(String value) {
            addCriterion("upd_user_id >", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user_id >=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThan(String value) {
            addCriterion("upd_user_id <", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("upd_user_id <=", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdLike(String value) {
            addCriterion("upd_user_id like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotLike(String value) {
            addCriterion("upd_user_id not like", value, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdIn(List<String> values) {
            addCriterion("upd_user_id in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotIn(List<String> values) {
            addCriterion("upd_user_id not in", values, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdBetween(String value1, String value2) {
            addCriterion("upd_user_id between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("upd_user_id not between", value1, value2, "updUserId");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(String value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(String value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(String value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(String value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(String value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(String value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLike(String value) {
            addCriterion("upd_time like", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotLike(String value) {
            addCriterion("upd_time not like", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<String> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<String> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(String value1, String value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(String value1, String value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNull() {
            addCriterion("sys_flag is null");
            return (Criteria) this;
        }

        public Criteria andSysFlagIsNotNull() {
            addCriterion("sys_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSysFlagEqualTo(String value) {
            addCriterion("sys_flag =", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotEqualTo(String value) {
            addCriterion("sys_flag <>", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThan(String value) {
            addCriterion("sys_flag >", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagGreaterThanOrEqualTo(String value) {
            addCriterion("sys_flag >=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThan(String value) {
            addCriterion("sys_flag <", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLessThanOrEqualTo(String value) {
            addCriterion("sys_flag <=", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagLike(String value) {
            addCriterion("sys_flag like", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotLike(String value) {
            addCriterion("sys_flag not like", value, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagIn(List<String> values) {
            addCriterion("sys_flag in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotIn(List<String> values) {
            addCriterion("sys_flag not in", values, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagBetween(String value1, String value2) {
            addCriterion("sys_flag between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andSysFlagNotBetween(String value1, String value2) {
            addCriterion("sys_flag not between", value1, value2, "sysFlag");
            return (Criteria) this;
        }

        public Criteria andOperateIdIsNull() {
            addCriterion("operate_id is null");
            return (Criteria) this;
        }

        public Criteria andOperateIdIsNotNull() {
            addCriterion("operate_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperateIdEqualTo(String value) {
            addCriterion("operate_id =", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotEqualTo(String value) {
            addCriterion("operate_id <>", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdGreaterThan(String value) {
            addCriterion("operate_id >", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdGreaterThanOrEqualTo(String value) {
            addCriterion("operate_id >=", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdLessThan(String value) {
            addCriterion("operate_id <", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdLessThanOrEqualTo(String value) {
            addCriterion("operate_id <=", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdLike(String value) {
            addCriterion("operate_id like", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotLike(String value) {
            addCriterion("operate_id not like", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdIn(List<String> values) {
            addCriterion("operate_id in", values, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotIn(List<String> values) {
            addCriterion("operate_id not in", values, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdBetween(String value1, String value2) {
            addCriterion("operate_id between", value1, value2, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotBetween(String value1, String value2) {
            addCriterion("operate_id not between", value1, value2, "operateId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 15 21:04:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}