package com.bsms.app.model;

public class TblEeqUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.pk_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private Long pkEeqUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.dept_code
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.bran_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String branId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.user_name
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.user_pwd
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.user_state
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String userState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.memo
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.tel_no
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.fax_no
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String faxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.email_addr
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String emailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.lstin_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String lstinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.lstout_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String lstoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.chgpwd_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String chgpwdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.session_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.cur_state
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String curState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.crt_user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String crtUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.crt_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.upd_user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String updUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.upd_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.sys_flag
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String sysFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_eeq_user.operate_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    private String operateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.pk_eeq_user
     *
     * @return the value of tbl_eeq_user.pk_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public Long getPkEeqUser() {
        return pkEeqUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.pk_eeq_user
     *
     * @param pkEeqUser the value for tbl_eeq_user.pk_eeq_user
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setPkEeqUser(Long pkEeqUser) {
        this.pkEeqUser = pkEeqUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.dept_code
     *
     * @return the value of tbl_eeq_user.dept_code
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.dept_code
     *
     * @param deptCode the value for tbl_eeq_user.dept_code
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.bran_id
     *
     * @return the value of tbl_eeq_user.bran_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getBranId() {
        return branId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.bran_id
     *
     * @param branId the value for tbl_eeq_user.bran_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setBranId(String branId) {
        this.branId = branId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.user_id
     *
     * @return the value of tbl_eeq_user.user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.user_id
     *
     * @param userId the value for tbl_eeq_user.user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.user_name
     *
     * @return the value of tbl_eeq_user.user_name
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.user_name
     *
     * @param userName the value for tbl_eeq_user.user_name
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.user_pwd
     *
     * @return the value of tbl_eeq_user.user_pwd
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.user_pwd
     *
     * @param userPwd the value for tbl_eeq_user.user_pwd
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.user_state
     *
     * @return the value of tbl_eeq_user.user_state
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.user_state
     *
     * @param userState the value for tbl_eeq_user.user_state
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setUserState(String userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.memo
     *
     * @return the value of tbl_eeq_user.memo
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.memo
     *
     * @param memo the value for tbl_eeq_user.memo
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.tel_no
     *
     * @return the value of tbl_eeq_user.tel_no
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.tel_no
     *
     * @param telNo the value for tbl_eeq_user.tel_no
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.fax_no
     *
     * @return the value of tbl_eeq_user.fax_no
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getFaxNo() {
        return faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.fax_no
     *
     * @param faxNo the value for tbl_eeq_user.fax_no
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.email_addr
     *
     * @return the value of tbl_eeq_user.email_addr
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.email_addr
     *
     * @param emailAddr the value for tbl_eeq_user.email_addr
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.lstin_time
     *
     * @return the value of tbl_eeq_user.lstin_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getLstinTime() {
        return lstinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.lstin_time
     *
     * @param lstinTime the value for tbl_eeq_user.lstin_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setLstinTime(String lstinTime) {
        this.lstinTime = lstinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.lstout_time
     *
     * @return the value of tbl_eeq_user.lstout_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getLstoutTime() {
        return lstoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.lstout_time
     *
     * @param lstoutTime the value for tbl_eeq_user.lstout_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setLstoutTime(String lstoutTime) {
        this.lstoutTime = lstoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.chgpwd_time
     *
     * @return the value of tbl_eeq_user.chgpwd_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getChgpwdTime() {
        return chgpwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.chgpwd_time
     *
     * @param chgpwdTime the value for tbl_eeq_user.chgpwd_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setChgpwdTime(String chgpwdTime) {
        this.chgpwdTime = chgpwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.session_id
     *
     * @return the value of tbl_eeq_user.session_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.session_id
     *
     * @param sessionId the value for tbl_eeq_user.session_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.cur_state
     *
     * @return the value of tbl_eeq_user.cur_state
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getCurState() {
        return curState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.cur_state
     *
     * @param curState the value for tbl_eeq_user.cur_state
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setCurState(String curState) {
        this.curState = curState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.crt_user_id
     *
     * @return the value of tbl_eeq_user.crt_user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getCrtUserId() {
        return crtUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.crt_user_id
     *
     * @param crtUserId the value for tbl_eeq_user.crt_user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setCrtUserId(String crtUserId) {
        this.crtUserId = crtUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.crt_time
     *
     * @return the value of tbl_eeq_user.crt_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.crt_time
     *
     * @param crtTime the value for tbl_eeq_user.crt_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setCrtTime(String crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.upd_user_id
     *
     * @return the value of tbl_eeq_user.upd_user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getUpdUserId() {
        return updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.upd_user_id
     *
     * @param updUserId the value for tbl_eeq_user.upd_user_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setUpdUserId(String updUserId) {
        this.updUserId = updUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.upd_time
     *
     * @return the value of tbl_eeq_user.upd_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.upd_time
     *
     * @param updTime the value for tbl_eeq_user.upd_time
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setUpdTime(String updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.sys_flag
     *
     * @return the value of tbl_eeq_user.sys_flag
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getSysFlag() {
        return sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.sys_flag
     *
     * @param sysFlag the value for tbl_eeq_user.sys_flag
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setSysFlag(String sysFlag) {
        this.sysFlag = sysFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_eeq_user.operate_id
     *
     * @return the value of tbl_eeq_user.operate_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public String getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_eeq_user.operate_id
     *
     * @param operateId the value for tbl_eeq_user.operate_id
     *
     * @mbg.generated Thu Nov 15 21:04:22 CST 2018
     */
    public void setOperateId(String operateId) {
        this.operateId = operateId;
    }
}