package com.bsms.app.model;

import java.util.ArrayList;
import java.util.List;

public class TblMarketingActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public TblMarketingActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActivityCodeIsNull() {
            addCriterion("Activity_code is null");
            return (Criteria) this;
        }

        public Criteria andActivityCodeIsNotNull() {
            addCriterion("Activity_code is not null");
            return (Criteria) this;
        }

        public Criteria andActivityCodeEqualTo(String value) {
            addCriterion("Activity_code =", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotEqualTo(String value) {
            addCriterion("Activity_code <>", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeGreaterThan(String value) {
            addCriterion("Activity_code >", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_code >=", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeLessThan(String value) {
            addCriterion("Activity_code <", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeLessThanOrEqualTo(String value) {
            addCriterion("Activity_code <=", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeLike(String value) {
            addCriterion("Activity_code like", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotLike(String value) {
            addCriterion("Activity_code not like", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeIn(List<String> values) {
            addCriterion("Activity_code in", values, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotIn(List<String> values) {
            addCriterion("Activity_code not in", values, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeBetween(String value1, String value2) {
            addCriterion("Activity_code between", value1, value2, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotBetween(String value1, String value2) {
            addCriterion("Activity_code not between", value1, value2, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityNameIsNull() {
            addCriterion("Activity_name is null");
            return (Criteria) this;
        }

        public Criteria andActivityNameIsNotNull() {
            addCriterion("Activity_name is not null");
            return (Criteria) this;
        }

        public Criteria andActivityNameEqualTo(String value) {
            addCriterion("Activity_name =", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotEqualTo(String value) {
            addCriterion("Activity_name <>", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameGreaterThan(String value) {
            addCriterion("Activity_name >", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_name >=", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLessThan(String value) {
            addCriterion("Activity_name <", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLessThanOrEqualTo(String value) {
            addCriterion("Activity_name <=", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLike(String value) {
            addCriterion("Activity_name like", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotLike(String value) {
            addCriterion("Activity_name not like", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameIn(List<String> values) {
            addCriterion("Activity_name in", values, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotIn(List<String> values) {
            addCriterion("Activity_name not in", values, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameBetween(String value1, String value2) {
            addCriterion("Activity_name between", value1, value2, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotBetween(String value1, String value2) {
            addCriterion("Activity_name not between", value1, value2, "activityName");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("Start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("Start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("Start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("Start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("Start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("Start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("Start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("Start_time like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("Start_time not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("Start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("Start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("Start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("Start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("End_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("End_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("End_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("End_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("End_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("End_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("End_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("End_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("End_time like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("End_time not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("End_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("End_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("End_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("End_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("Card_type is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("Card_type is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("Card_type =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("Card_type <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("Card_type >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Card_type >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("Card_type <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("Card_type <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("Card_type like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("Card_type not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("Card_type in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("Card_type not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("Card_type between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("Card_type not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andJfTypeIsNull() {
            addCriterion("Jf_type is null");
            return (Criteria) this;
        }

        public Criteria andJfTypeIsNotNull() {
            addCriterion("Jf_type is not null");
            return (Criteria) this;
        }

        public Criteria andJfTypeEqualTo(String value) {
            addCriterion("Jf_type =", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeNotEqualTo(String value) {
            addCriterion("Jf_type <>", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeGreaterThan(String value) {
            addCriterion("Jf_type >", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Jf_type >=", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeLessThan(String value) {
            addCriterion("Jf_type <", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeLessThanOrEqualTo(String value) {
            addCriterion("Jf_type <=", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeLike(String value) {
            addCriterion("Jf_type like", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeNotLike(String value) {
            addCriterion("Jf_type not like", value, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeIn(List<String> values) {
            addCriterion("Jf_type in", values, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeNotIn(List<String> values) {
            addCriterion("Jf_type not in", values, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeBetween(String value1, String value2) {
            addCriterion("Jf_type between", value1, value2, "jfType");
            return (Criteria) this;
        }

        public Criteria andJfTypeNotBetween(String value1, String value2) {
            addCriterion("Jf_type not between", value1, value2, "jfType");
            return (Criteria) this;
        }

        public Criteria andActivityExplainIsNull() {
            addCriterion("Activity_explain is null");
            return (Criteria) this;
        }

        public Criteria andActivityExplainIsNotNull() {
            addCriterion("Activity_explain is not null");
            return (Criteria) this;
        }

        public Criteria andActivityExplainEqualTo(String value) {
            addCriterion("Activity_explain =", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainNotEqualTo(String value) {
            addCriterion("Activity_explain <>", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainGreaterThan(String value) {
            addCriterion("Activity_explain >", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_explain >=", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainLessThan(String value) {
            addCriterion("Activity_explain <", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainLessThanOrEqualTo(String value) {
            addCriterion("Activity_explain <=", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainLike(String value) {
            addCriterion("Activity_explain like", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainNotLike(String value) {
            addCriterion("Activity_explain not like", value, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainIn(List<String> values) {
            addCriterion("Activity_explain in", values, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainNotIn(List<String> values) {
            addCriterion("Activity_explain not in", values, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainBetween(String value1, String value2) {
            addCriterion("Activity_explain between", value1, value2, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityExplainNotBetween(String value1, String value2) {
            addCriterion("Activity_explain not between", value1, value2, "activityExplain");
            return (Criteria) this;
        }

        public Criteria andActivityLinkIsNull() {
            addCriterion("Activity_link is null");
            return (Criteria) this;
        }

        public Criteria andActivityLinkIsNotNull() {
            addCriterion("Activity_link is not null");
            return (Criteria) this;
        }

        public Criteria andActivityLinkEqualTo(String value) {
            addCriterion("Activity_link =", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkNotEqualTo(String value) {
            addCriterion("Activity_link <>", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkGreaterThan(String value) {
            addCriterion("Activity_link >", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_link >=", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkLessThan(String value) {
            addCriterion("Activity_link <", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkLessThanOrEqualTo(String value) {
            addCriterion("Activity_link <=", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkLike(String value) {
            addCriterion("Activity_link like", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkNotLike(String value) {
            addCriterion("Activity_link not like", value, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkIn(List<String> values) {
            addCriterion("Activity_link in", values, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkNotIn(List<String> values) {
            addCriterion("Activity_link not in", values, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkBetween(String value1, String value2) {
            addCriterion("Activity_link between", value1, value2, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityLinkNotBetween(String value1, String value2) {
            addCriterion("Activity_link not between", value1, value2, "activityLink");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescIsNull() {
            addCriterion("Activity_target_desc is null");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescIsNotNull() {
            addCriterion("Activity_target_desc is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescEqualTo(String value) {
            addCriterion("Activity_target_desc =", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescNotEqualTo(String value) {
            addCriterion("Activity_target_desc <>", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescGreaterThan(String value) {
            addCriterion("Activity_target_desc >", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_target_desc >=", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescLessThan(String value) {
            addCriterion("Activity_target_desc <", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescLessThanOrEqualTo(String value) {
            addCriterion("Activity_target_desc <=", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescLike(String value) {
            addCriterion("Activity_target_desc like", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescNotLike(String value) {
            addCriterion("Activity_target_desc not like", value, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescIn(List<String> values) {
            addCriterion("Activity_target_desc in", values, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescNotIn(List<String> values) {
            addCriterion("Activity_target_desc not in", values, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescBetween(String value1, String value2) {
            addCriterion("Activity_target_desc between", value1, value2, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetDescNotBetween(String value1, String value2) {
            addCriterion("Activity_target_desc not between", value1, value2, "activityTargetDesc");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeIsNull() {
            addCriterion("Activity_target_type is null");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeIsNotNull() {
            addCriterion("Activity_target_type is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeEqualTo(String value) {
            addCriterion("Activity_target_type =", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeNotEqualTo(String value) {
            addCriterion("Activity_target_type <>", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeGreaterThan(String value) {
            addCriterion("Activity_target_type >", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_target_type >=", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeLessThan(String value) {
            addCriterion("Activity_target_type <", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeLessThanOrEqualTo(String value) {
            addCriterion("Activity_target_type <=", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeLike(String value) {
            addCriterion("Activity_target_type like", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeNotLike(String value) {
            addCriterion("Activity_target_type not like", value, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeIn(List<String> values) {
            addCriterion("Activity_target_type in", values, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeNotIn(List<String> values) {
            addCriterion("Activity_target_type not in", values, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeBetween(String value1, String value2) {
            addCriterion("Activity_target_type between", value1, value2, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetTypeNotBetween(String value1, String value2) {
            addCriterion("Activity_target_type not between", value1, value2, "activityTargetType");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumIsNull() {
            addCriterion("Activity_target_num is null");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumIsNotNull() {
            addCriterion("Activity_target_num is not null");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumEqualTo(String value) {
            addCriterion("Activity_target_num =", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumNotEqualTo(String value) {
            addCriterion("Activity_target_num <>", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumGreaterThan(String value) {
            addCriterion("Activity_target_num >", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumGreaterThanOrEqualTo(String value) {
            addCriterion("Activity_target_num >=", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumLessThan(String value) {
            addCriterion("Activity_target_num <", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumLessThanOrEqualTo(String value) {
            addCriterion("Activity_target_num <=", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumLike(String value) {
            addCriterion("Activity_target_num like", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumNotLike(String value) {
            addCriterion("Activity_target_num not like", value, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumIn(List<String> values) {
            addCriterion("Activity_target_num in", values, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumNotIn(List<String> values) {
            addCriterion("Activity_target_num not in", values, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumBetween(String value1, String value2) {
            addCriterion("Activity_target_num between", value1, value2, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andActivityTargetNumNotBetween(String value1, String value2) {
            addCriterion("Activity_target_num not between", value1, value2, "activityTargetNum");
            return (Criteria) this;
        }

        public Criteria andCardNumIsNull() {
            addCriterion("Card_num is null");
            return (Criteria) this;
        }

        public Criteria andCardNumIsNotNull() {
            addCriterion("Card_num is not null");
            return (Criteria) this;
        }

        public Criteria andCardNumEqualTo(String value) {
            addCriterion("Card_num =", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumNotEqualTo(String value) {
            addCriterion("Card_num <>", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumGreaterThan(String value) {
            addCriterion("Card_num >", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumGreaterThanOrEqualTo(String value) {
            addCriterion("Card_num >=", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumLessThan(String value) {
            addCriterion("Card_num <", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumLessThanOrEqualTo(String value) {
            addCriterion("Card_num <=", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumLike(String value) {
            addCriterion("Card_num like", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumNotLike(String value) {
            addCriterion("Card_num not like", value, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumIn(List<String> values) {
            addCriterion("Card_num in", values, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumNotIn(List<String> values) {
            addCriterion("Card_num not in", values, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumBetween(String value1, String value2) {
            addCriterion("Card_num between", value1, value2, "cardNum");
            return (Criteria) this;
        }

        public Criteria andCardNumNotBetween(String value1, String value2) {
            addCriterion("Card_num not between", value1, value2, "cardNum");
            return (Criteria) this;
        }

        public Criteria andJfNumIsNull() {
            addCriterion("Jf_num is null");
            return (Criteria) this;
        }

        public Criteria andJfNumIsNotNull() {
            addCriterion("Jf_num is not null");
            return (Criteria) this;
        }

        public Criteria andJfNumEqualTo(String value) {
            addCriterion("Jf_num =", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumNotEqualTo(String value) {
            addCriterion("Jf_num <>", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumGreaterThan(String value) {
            addCriterion("Jf_num >", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumGreaterThanOrEqualTo(String value) {
            addCriterion("Jf_num >=", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumLessThan(String value) {
            addCriterion("Jf_num <", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumLessThanOrEqualTo(String value) {
            addCriterion("Jf_num <=", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumLike(String value) {
            addCriterion("Jf_num like", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumNotLike(String value) {
            addCriterion("Jf_num not like", value, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumIn(List<String> values) {
            addCriterion("Jf_num in", values, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumNotIn(List<String> values) {
            addCriterion("Jf_num not in", values, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumBetween(String value1, String value2) {
            addCriterion("Jf_num between", value1, value2, "jfNum");
            return (Criteria) this;
        }

        public Criteria andJfNumNotBetween(String value1, String value2) {
            addCriterion("Jf_num not between", value1, value2, "jfNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("Create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("Create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("Create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("Create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("Create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("Create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("Create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("Create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("Create_date like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("Create_date not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("Create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("Create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("Create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("Create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("Create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("Create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("Create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("Create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("Create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("Create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("Create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("Create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("Create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("Create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("Create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("Create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("Create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("Create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("Create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("Create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("Create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("Create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("Create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("Create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("Create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("Create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("Create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("Create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("Create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("Create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("Create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andSubmitDateIsNull() {
            addCriterion("Submit_date is null");
            return (Criteria) this;
        }

        public Criteria andSubmitDateIsNotNull() {
            addCriterion("Submit_date is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitDateEqualTo(String value) {
            addCriterion("Submit_date =", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotEqualTo(String value) {
            addCriterion("Submit_date <>", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateGreaterThan(String value) {
            addCriterion("Submit_date >", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateGreaterThanOrEqualTo(String value) {
            addCriterion("Submit_date >=", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateLessThan(String value) {
            addCriterion("Submit_date <", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateLessThanOrEqualTo(String value) {
            addCriterion("Submit_date <=", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateLike(String value) {
            addCriterion("Submit_date like", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotLike(String value) {
            addCriterion("Submit_date not like", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateIn(List<String> values) {
            addCriterion("Submit_date in", values, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotIn(List<String> values) {
            addCriterion("Submit_date not in", values, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateBetween(String value1, String value2) {
            addCriterion("Submit_date between", value1, value2, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotBetween(String value1, String value2) {
            addCriterion("Submit_date not between", value1, value2, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIsNull() {
            addCriterion("Submit_time is null");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIsNotNull() {
            addCriterion("Submit_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeEqualTo(String value) {
            addCriterion("Submit_time =", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotEqualTo(String value) {
            addCriterion("Submit_time <>", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeGreaterThan(String value) {
            addCriterion("Submit_time >", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Submit_time >=", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLessThan(String value) {
            addCriterion("Submit_time <", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLessThanOrEqualTo(String value) {
            addCriterion("Submit_time <=", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLike(String value) {
            addCriterion("Submit_time like", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotLike(String value) {
            addCriterion("Submit_time not like", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIn(List<String> values) {
            addCriterion("Submit_time in", values, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotIn(List<String> values) {
            addCriterion("Submit_time not in", values, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeBetween(String value1, String value2) {
            addCriterion("Submit_time between", value1, value2, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotBetween(String value1, String value2) {
            addCriterion("Submit_time not between", value1, value2, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIsNull() {
            addCriterion("Submit_user is null");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIsNotNull() {
            addCriterion("Submit_user is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitUserEqualTo(String value) {
            addCriterion("Submit_user =", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserNotEqualTo(String value) {
            addCriterion("Submit_user <>", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserGreaterThan(String value) {
            addCriterion("Submit_user >", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserGreaterThanOrEqualTo(String value) {
            addCriterion("Submit_user >=", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserLessThan(String value) {
            addCriterion("Submit_user <", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserLessThanOrEqualTo(String value) {
            addCriterion("Submit_user <=", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserLike(String value) {
            addCriterion("Submit_user like", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserNotLike(String value) {
            addCriterion("Submit_user not like", value, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserIn(List<String> values) {
            addCriterion("Submit_user in", values, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserNotIn(List<String> values) {
            addCriterion("Submit_user not in", values, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserBetween(String value1, String value2) {
            addCriterion("Submit_user between", value1, value2, "submitUser");
            return (Criteria) this;
        }

        public Criteria andSubmitUserNotBetween(String value1, String value2) {
            addCriterion("Submit_user not between", value1, value2, "submitUser");
            return (Criteria) this;
        }

        public Criteria andApproveDateIsNull() {
            addCriterion("Approve_date is null");
            return (Criteria) this;
        }

        public Criteria andApproveDateIsNotNull() {
            addCriterion("Approve_date is not null");
            return (Criteria) this;
        }

        public Criteria andApproveDateEqualTo(String value) {
            addCriterion("Approve_date =", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotEqualTo(String value) {
            addCriterion("Approve_date <>", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateGreaterThan(String value) {
            addCriterion("Approve_date >", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateGreaterThanOrEqualTo(String value) {
            addCriterion("Approve_date >=", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLessThan(String value) {
            addCriterion("Approve_date <", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLessThanOrEqualTo(String value) {
            addCriterion("Approve_date <=", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLike(String value) {
            addCriterion("Approve_date like", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotLike(String value) {
            addCriterion("Approve_date not like", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateIn(List<String> values) {
            addCriterion("Approve_date in", values, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotIn(List<String> values) {
            addCriterion("Approve_date not in", values, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateBetween(String value1, String value2) {
            addCriterion("Approve_date between", value1, value2, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotBetween(String value1, String value2) {
            addCriterion("Approve_date not between", value1, value2, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNull() {
            addCriterion("Approve_time is null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNotNull() {
            addCriterion("Approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeEqualTo(String value) {
            addCriterion("Approve_time =", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotEqualTo(String value) {
            addCriterion("Approve_time <>", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThan(String value) {
            addCriterion("Approve_time >", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Approve_time >=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThan(String value) {
            addCriterion("Approve_time <", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThanOrEqualTo(String value) {
            addCriterion("Approve_time <=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLike(String value) {
            addCriterion("Approve_time like", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotLike(String value) {
            addCriterion("Approve_time not like", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIn(List<String> values) {
            addCriterion("Approve_time in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotIn(List<String> values) {
            addCriterion("Approve_time not in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeBetween(String value1, String value2) {
            addCriterion("Approve_time between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotBetween(String value1, String value2) {
            addCriterion("Approve_time not between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveUserIsNull() {
            addCriterion("Approve_user is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIsNotNull() {
            addCriterion("Approve_user is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserEqualTo(String value) {
            addCriterion("Approve_user =", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserNotEqualTo(String value) {
            addCriterion("Approve_user <>", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserGreaterThan(String value) {
            addCriterion("Approve_user >", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserGreaterThanOrEqualTo(String value) {
            addCriterion("Approve_user >=", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserLessThan(String value) {
            addCriterion("Approve_user <", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserLessThanOrEqualTo(String value) {
            addCriterion("Approve_user <=", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserLike(String value) {
            addCriterion("Approve_user like", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserNotLike(String value) {
            addCriterion("Approve_user not like", value, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserIn(List<String> values) {
            addCriterion("Approve_user in", values, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserNotIn(List<String> values) {
            addCriterion("Approve_user not in", values, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserBetween(String value1, String value2) {
            addCriterion("Approve_user between", value1, value2, "approveUser");
            return (Criteria) this;
        }

        public Criteria andApproveUserNotBetween(String value1, String value2) {
            addCriterion("Approve_user not between", value1, value2, "approveUser");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 15 20:59:20 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_marketing_activity
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}