package com.bsms.app.model;

public class TblMarketingActivity extends Page{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.id
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_code
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_name
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Start_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.End_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Card_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Jf_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String jfType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_explain
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityExplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_link
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_target_desc
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityTargetDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_target_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityTargetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Activity_target_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String activityTargetNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Card_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String cardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Jf_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String jfNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.status
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Create_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Create_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Create_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Submit_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String submitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Submit_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Submit_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String submitUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Approve_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String approveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Approve_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String approveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Approve_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String approveUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_marketing_activity.Comment
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.id
     *
     * @return the value of tbl_marketing_activity.id
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.id
     *
     * @param id the value for tbl_marketing_activity.id
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_code
     *
     * @return the value of tbl_marketing_activity.Activity_code
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_code
     *
     * @param activityCode the value for tbl_marketing_activity.Activity_code
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_name
     *
     * @return the value of tbl_marketing_activity.Activity_name
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_name
     *
     * @param activityName the value for tbl_marketing_activity.Activity_name
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Start_time
     *
     * @return the value of tbl_marketing_activity.Start_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Start_time
     *
     * @param startTime the value for tbl_marketing_activity.Start_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.End_time
     *
     * @return the value of tbl_marketing_activity.End_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.End_time
     *
     * @param endTime the value for tbl_marketing_activity.End_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Card_type
     *
     * @return the value of tbl_marketing_activity.Card_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Card_type
     *
     * @param cardType the value for tbl_marketing_activity.Card_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Jf_type
     *
     * @return the value of tbl_marketing_activity.Jf_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getJfType() {
        return jfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Jf_type
     *
     * @param jfType the value for tbl_marketing_activity.Jf_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setJfType(String jfType) {
        this.jfType = jfType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_explain
     *
     * @return the value of tbl_marketing_activity.Activity_explain
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityExplain() {
        return activityExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_explain
     *
     * @param activityExplain the value for tbl_marketing_activity.Activity_explain
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityExplain(String activityExplain) {
        this.activityExplain = activityExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_link
     *
     * @return the value of tbl_marketing_activity.Activity_link
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityLink() {
        return activityLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_link
     *
     * @param activityLink the value for tbl_marketing_activity.Activity_link
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityLink(String activityLink) {
        this.activityLink = activityLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_target_desc
     *
     * @return the value of tbl_marketing_activity.Activity_target_desc
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityTargetDesc() {
        return activityTargetDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_target_desc
     *
     * @param activityTargetDesc the value for tbl_marketing_activity.Activity_target_desc
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityTargetDesc(String activityTargetDesc) {
        this.activityTargetDesc = activityTargetDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_target_type
     *
     * @return the value of tbl_marketing_activity.Activity_target_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityTargetType() {
        return activityTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_target_type
     *
     * @param activityTargetType the value for tbl_marketing_activity.Activity_target_type
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityTargetType(String activityTargetType) {
        this.activityTargetType = activityTargetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Activity_target_num
     *
     * @return the value of tbl_marketing_activity.Activity_target_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getActivityTargetNum() {
        return activityTargetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Activity_target_num
     *
     * @param activityTargetNum the value for tbl_marketing_activity.Activity_target_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setActivityTargetNum(String activityTargetNum) {
        this.activityTargetNum = activityTargetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Card_num
     *
     * @return the value of tbl_marketing_activity.Card_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Card_num
     *
     * @param cardNum the value for tbl_marketing_activity.Card_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Jf_num
     *
     * @return the value of tbl_marketing_activity.Jf_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getJfNum() {
        return jfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Jf_num
     *
     * @param jfNum the value for tbl_marketing_activity.Jf_num
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setJfNum(String jfNum) {
        this.jfNum = jfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.status
     *
     * @return the value of tbl_marketing_activity.status
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.status
     *
     * @param status the value for tbl_marketing_activity.status
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Create_date
     *
     * @return the value of tbl_marketing_activity.Create_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Create_date
     *
     * @param createDate the value for tbl_marketing_activity.Create_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Create_time
     *
     * @return the value of tbl_marketing_activity.Create_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Create_time
     *
     * @param createTime the value for tbl_marketing_activity.Create_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Create_user
     *
     * @return the value of tbl_marketing_activity.Create_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Create_user
     *
     * @param createUser the value for tbl_marketing_activity.Create_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Submit_date
     *
     * @return the value of tbl_marketing_activity.Submit_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Submit_date
     *
     * @param submitDate the value for tbl_marketing_activity.Submit_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setSubmitDate(String submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Submit_time
     *
     * @return the value of tbl_marketing_activity.Submit_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Submit_time
     *
     * @param submitTime the value for tbl_marketing_activity.Submit_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setSubmitTime(String submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Submit_user
     *
     * @return the value of tbl_marketing_activity.Submit_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getSubmitUser() {
        return submitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Submit_user
     *
     * @param submitUser the value for tbl_marketing_activity.Submit_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setSubmitUser(String submitUser) {
        this.submitUser = submitUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Approve_date
     *
     * @return the value of tbl_marketing_activity.Approve_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Approve_date
     *
     * @param approveDate the value for tbl_marketing_activity.Approve_date
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setApproveDate(String approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Approve_time
     *
     * @return the value of tbl_marketing_activity.Approve_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Approve_time
     *
     * @param approveTime the value for tbl_marketing_activity.Approve_time
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setApproveTime(String approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Approve_user
     *
     * @return the value of tbl_marketing_activity.Approve_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getApproveUser() {
        return approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Approve_user
     *
     * @param approveUser the value for tbl_marketing_activity.Approve_user
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setApproveUser(String approveUser) {
        this.approveUser = approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_marketing_activity.Comment
     *
     * @return the value of tbl_marketing_activity.Comment
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_marketing_activity.Comment
     *
     * @param comment the value for tbl_marketing_activity.Comment
     *
     * @mbg.generated Thu Nov 15 20:59:20 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}